### PR TITLE
airflow 2 upgrade

### PR DESCRIPTION
**Pull request by de-code**
part of https://github.com/elifesciences/sciencebeam-issues/issues/80

### CODE REVIEW

**Comment by de-code** [comment]
Remaining issues:

- two training DAGs need to be refactored
- web UI needs authentication

**Comment by de-code** [comment]
Now getting the following error when running the tests:

```
$ make dev-pytest 
GOOGLE_CLOUD_PROJECT=dummy \
SCIENCEBEAM_CONFIG_DATA_PATH=gs://dummy \
SCIENCEBEAM_WATCH_INTERVAL=1000 \
PYTHONPATH=dags venv/bin/python -m pytest -p no:cacheprovider 
/path/to/sciencebeam-airflow/venv/lib/python3.8/site-packages/airflow/configuration.py:324 DeprecationWarning: The logging_config_class option in [core] has been moved to the logging_config_class option in [logging] - the old setting has been used, but please update your config.
/path/to/sciencebeam-airflow/venv/lib/python3.8/site-packages/airflow/configuration.py:324 DeprecationWarning: The logging_level option in [core] has been moved to the logging_level option in [logging] - the old setting has been used, but please update your config.
/path/to/sciencebeam-airflow/venv/lib/python3.8/site-packages/airflow/configuration.py:324 DeprecationWarning: The base_log_folder option in [core] has been moved to the base_log_folder option in [logging] - the old setting has been used, but please update your config.
/path/to/sciencebeam-airflow/venv/lib/python3.8/site-packages/airflow/configuration.py:324 DeprecationWarning: The task_log_reader option in [core] has been moved to the task_log_reader option in [logging] - the old setting has been used, but please update your config.
/path/to/sciencebeam-airflow/venv/lib/python3.8/site-packages/airflow/logging_config.py:82 DeprecationWarning: task_log_reader setting in [logging] has a deprecated value of 'file.task', but no handler with this name was found. Please update your config to use 'task'. Running config has been adjusted to match
ImportError while loading conftest '/path/to/sciencebeam-airflow/tests/conftest.py'.
tests/conftest.py:6: in <module>
    import airflow
venv/lib/python3.8/site-packages/airflow/__init__.py:46: in <module>
    settings.initialize()
venv/lib/python3.8/site-packages/airflow/settings.py:432: in initialize
    LOGGING_CLASS_PATH = configure_logging()
venv/lib/python3.8/site-packages/airflow/logging_config.py:64: in configure_logging
    validate_logging_config(logging_config)
venv/lib/python3.8/site-packages/airflow/logging_config.py:92: in validate_logging_config
    conf.set('logging', 'task_log_reader', 'task')
/usr/lib/python3.8/configparser.py:1201: in set
    super().set(section, option, value)
/usr/lib/python3.8/configparser.py:902: in set
    raise NoSectionError(section) from None
E   configparser.NoSectionError: No section: 'logging'
make: *** [Makefile:124: dev-pytest] Error 4
```

**Comment by de-code** [comment]
Remaining issues:

- disable web ui authentication

**Comment by de-code** [comment]
While reading the Airflow code, I figured out how to disable the authentication by setting `AUTH_ROLE_PUBLIC = 'Admin'` in `$AIRFLOW_HOME/webserver_config.py`. That is currently undocumented but should be documented soon.
Unfortunately there is currently a bug https://github.com/apache/airflow/issues/13142
It seems to have been resolved, but not yet released.

**Review by HazalCiplak — APPROVED** [review]

**Comment by de-code** [comment]
This all seems to be working now.

**Pull request merged**
